version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - PORT=${PORT}
      - OMDB_KEY=${OMDB_KEY}
      - TMDB_KEY=${TMDB_KEY}
      - TVDB_KEY=${TVDB_KEY}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - CRON_TIME=${CRON_TIME}
      - TEMP_DIR=${TEMP_DIR}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/go/src/youvies-backend
      - go_mod_cache:/go/pkg/mod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  go_mod_cache:
