version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youvies-backend
    ports:
      - "127.0.0.1:5000"
    environment:
      - PORT=5000
      - POSTGRES_URI=${POSTGRES_URI}
      - CRON_TIME=${CRON_TIME}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/go/src/youvies-backend
      - go_mod_cache:/go/pkg/mod
    restart: unless-stopped


volumes:
  go_mod_cache: